apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: voyager
  name: voyager-operator
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: voyager
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - name: voyager
        args:
        - run
        - --v=3
        - --cloud-provider=$CLOUD_PROVIDER
        - --cloud-config=$CLOUD_CONFIG # ie. /etc/kubernetes/azure.json for azure
        - --ingress-class=$INGRESS_CLASS
        - --custom-templates=/srv/voyager/custom/*.cfg
        image: appscode/voyager:5.0.0-rc.6
        ports:
        - containerPort: 56790
          name: ops
          protocol: TCP
        - containerPort: 56791
          name: acme
          protocol: TCP
        volumeMounts:
          - mountPath: /etc/kubernetes
            name: cloudconfig
            readOnly: true
          - mountPath: /srv/voyager/custom
            name: templates
            readOnly: true
      volumes:
        - hostPath:
            path: /etc/kubernetes
          name: cloudconfig
        - configMap:
            name: voyager-templates
          name: templates
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
